resources:
- name: sample_resource
  type: git
  source:
    uri: https://git.sami.int.thomsonreuters.com/Mike.Spoonauer/concourse-tutorial.git
    branch: master

jobs:
- name: hello-world
  public: true
  plan:
  - get: sample_resource
  - task: hello-world
    file: sample_resource/tasks/hello_world.yml
