resources:
- name: sample_resource
  type: git
  source:
    uri: https://github.com/mike-spoonauer-rft/concourse-tutorial
    branch: master

jobs:
- name: hello-world
  public: true
  plan:
  - get: sample_resource
  - task: hello-world
    file: sample_resource/tasks/hello_world.yml
